# Stage 1: Build app
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Build duy nhất 1 bản với title là 'Carbon Credit Eco'
RUN REACT_APP_TITLE='Carbon Credit Eco' PUBLIC_URL='/' npm run build

# Stage 2: Serve với Nginx
FROM nginx:alpine
# Copy cấu hình Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy bản build vào thư mục gốc của nginx
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
